services:
  - type: web
    name: therapy-chat-app
    env: node
    buildCommand: |
      NODE_ENV=development npm ci && bash build-fix.sh
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: therapy-db
          property: connectionString
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_API_BASE
        value: https://api.cashfree.com/pg

databases:
  - name: therapy-db
    databaseName: therapy
    user: therapy
    plan: free